services:
  # Single MongoDB for all services
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "${MONGO_PORT:-27020}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./data/mongodb:/data/db
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - skillhub-network

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - skillhub-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - skillhub-network

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "${KAFKA_BROKER_PORT}:9092"
      - "${KAFKA_BROKER_INTERNAL_PORT}:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:${ZOOKEEPER_PORT}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:${KAFKA_BROKER_INTERNAL_PORT},PLAINTEXT_HOST://localhost:${KAFKA_BROKER_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    networks:
      - skillhub-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "${SCHEMA_REGISTRY_PORT}:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:${KAFKA_BROKER_INTERNAL_PORT}'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    networks:
      - skillhub-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "${KAFKA_UI_PORT}:8080"
    depends_on:
      - broker
      - schema-registry
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:${KAFKA_BROKER_INTERNAL_PORT}
      KAFKA_CLUSTERS_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - skillhub-network

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - skillhub-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.0
    command: [ "start-dev","--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8180
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
    ports:
      - "8180:8180"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - keycloak-mysql
    networks:
      - skillhub-network

  profile-service:
    image: profile-service:latest
    container_name: profile-service
    ports:
      - "${PROFILE_SERVICE_PORT}:${PROFILE_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PROFILE_SERVICE_PORT=${PROFILE_SERVICE_PORT}
      - TZ=Asia/Ho_Chi_Minh
      # MongoDB config
      - MONGO_ALL_ON_SYS=${MONGO_ALL_ON_SYS}
      - MONGO_USER_DATABASE=${MONGO_USER_DATABASE}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      # Keycloak config
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      #AWS config
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_PROFILE=${AWS_S3_BUCKET_PROFILE}
      # Kafka config
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      - KAFKA_BROKER_BOOTSTRAP_SERVER=${KAFKA_BROKER_BOOTSTRAP_SERVER}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
      # Other services URLs
      - ENROLLMENT_SERVICE_URL=${ENROLLMENT_SERVICE_URL}
      - COURSE_SERVICE_URL=${COURSE_SERVICE_URL}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL}
    depends_on:
      - mongodb
      - keycloak
      - broker
      - schema-registry
      - eureka-server
    networks:
      - skillhub-network

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - SPRING_PROFILES_ACTIVE=dev
      # Keycloak config
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - keycloak
      - eureka-server
    networks:
      - skillhub-network

  course-service:
    image: course-service:latest
    container_name: course-service
    ports:
      - "${COURSE_SERVICE_PORT}:${COURSE_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - COURSE_SERVICE_PORT=${COURSE_SERVICE_PORT}
      - TZ=Asia/Ho_Chi_Minh
      # MongoDB config
      - MONGO_ALL_ON_SYS=${MONGO_ALL_ON_SYS}
      - MONGO_COURSE_DATABASE=${MONGO_COURSE_DATABASE}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      # Keycloak config
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      #AWS config
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_COURSE=${AWS_S3_BUCKET_COURSE}
      # Kafka config
      - KAFKA_BROKER_BOOTSTRAP_SERVER=${KAFKA_BROKER_BOOTSTRAP_SERVER}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
      # Other services URLs
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      - LECTURE_SERVICE_URL=${LECTURE_SERVICE_URL}
      - ASSIGNMENT_SERVICE_URL=${ASSIGNMENT_SERVICE_URL}
      - EXAM_RESULTS_SERVICE_URL=${EXAM_RESULTS_SERVICE_URL}
      - ENROLLMENT_SERVICE_URL=${ENROLLMENT_SERVICE_URL}
    depends_on:
      - keycloak
      - profile-service
      - mongodb
      - eureka-server
    networks:
      - skillhub-network

  lecture-service:
    image: lecture-service:latest
    container_name: lecture-service
    ports:
      - "${LECTURE_SERVICE_PORT}:${LECTURE_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - LECTURE_SERVICE_PORT=${LECTURE_SERVICE_PORT}
      - TZ=Asia/Ho_Chi_Minh
      # MongoDB config
      - MONGO_ALL_ON_SYS=${MONGO_ALL_ON_SYS}
      - MONGO_LECTURE_DATABASE=${MONGO_LECTURE_DATABASE}
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_ROOT_USERNAME}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_ROOT_PASSWORD}
      # Keycloak config
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      # AWS config for video/file storage
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_LECTURE=${AWS_S3_BUCKET_LECTURE}
      # Kafka config
      - KAFKA_BROKER_BOOTSTRAP_SERVER=${KAFKA_BROKER_BOOTSTRAP_SERVER}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
    depends_on:
      - mongodb
      - keycloak
      - broker
      - schema-registry
      - eureka-server
    networks:
      - skillhub-network

  assignment-service:
    image: assignment-service:latest
    container_name: assignment-service
    ports:
      - "${ASSIGNMENT_SERVICE_PORT}:${ASSIGNMENT_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - ASSIGNMENT_SERVICE_PORT=${ASSIGNMENT_SERVICE_PORT}
      - TZ=Asia/Ho_Chi_Minh
      # MongoDB config
      - MONGO_ALL_ON_SYS=${MONGO_ALL_ON_SYS}
      - MONGO_ASSIGNMENT_DATABASE=${MONGO_ASSIGNMENT_DATABASE}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      # Keycloak config
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      # Kafka config
      - KAFKA_BROKER_BOOTSTRAP_SERVER=${KAFKA_BROKER_BOOTSTRAP_SERVER}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
      # Other services URLs
      - LECTURE_SERVICE_URL=${LECTURE_SERVICE_URL}
      - EXAM_RESULTS_SERVICE_URL=${EXAM_RESULTS_SERVICE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    depends_on:
      - mongodb
      - keycloak
      - broker
      - schema-registry
      - eureka-server
    networks:
      - skillhub-network

  blog-service:
    image: blog-service:latest
    container_name: blog-service
    ports:
      - "${BLOG_SERVICE_PORT}:${BLOG_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - BLOG_SERVICE_PORT=${BLOG_SERVICE_PORT}
      - TZ=Asia/Ho_Chi_Minh
      # MongoDB config
      - MONGO_ALL_ON_SYS=${MONGO_ALL_ON_SYS}
      - MONGO_BLOG_DATABASE=${MONGO_BLOG_DATABASE}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      # Keycloak config
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      # Kafka config
      - KAFKA_BROKER_BOOTSTRAP_SERVER=${KAFKA_BROKER_BOOTSTRAP_SERVER}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
      # Other services URLs
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      #AWS config
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_BLOG=${AWS_S3_BUCKET_BLOG}
    depends_on:
      - mongodb
      - keycloak
      - broker
      - schema-registry
      - eureka-server
    networks:
      - skillhub-network

  chat-service:
    image: chat-service:latest
    container_name: chat-service
    ports:
      - "${CHAT_SERVICE_PORT}:${CHAT_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CHAT_SERVICE_PORT=${CHAT_SERVICE_PORT}
      - TZ=Asia/Ho_Chi_Minh
      # MongoDB config
      - MONGO_ALL_ON_SYS=${MONGO_ALL_ON_SYS}
      - MONGO_CHAT_DATABASE=${MONGO_CHAT_DATABASE}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      # Keycloak config
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
    depends_on:
      - mongodb
      - keycloak
      - eureka-server
    networks:
      - skillhub-network

  exam-result-service:
    image: exam-result-service:latest
    container_name: exam-result-service
    ports:
      - "${EXAM_SERVICE_PORT}:${EXAM_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EXAM_SERVICE_PORT=${EXAM_SERVICE_PORT}
      - TZ=Asia/Ho_Chi_Minh
      # MongoDB config
      - MONGO_ALL_ON_SYS=${MONGO_ALL_ON_SYS}
      - MONGO_EXAM_RESULTS_DATABASE=${MONGO_EXAM_RESULTS_DATABASE}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      # Keycloak config
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      # Kafka config
      - KAFKA_BROKER_BOOTSTRAP_SERVER=${KAFKA_BROKER_BOOTSTRAP_SERVER}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
      # Other services URLs
      - ASSIGNMENT_SERVICE_URL=${ASSIGNMENT_SERVICE_URL}
    depends_on:
      - mongodb
      - keycloak
      - broker
      - schema-registry
      - eureka-server
    networks:
      - skillhub-network

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    environment:
      - NOTIFICATION_SERVICE_PORT=${NOTIFICATION_SERVICE_PORT}
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Ho_Chi_Minh
      - MAILTRAP_MAIL_HOST=${MAILTRAP_MAIL_HOST}
      - MAILTRAP_MAIL_PORT=${MAILTRAP_MAIL_PORT}
      - MAILTRAP_MAIL_USERNAME=${MAILTRAP_MAIL_USERNAME}
      - MAILTRAP_MAIL_PASSWORD=${MAILTRAP_MAIL_PASSWORD}
      - KAFKA_BROKER_BOOTSTRAP_SERVER=${KAFKA_BROKER_BOOTSTRAP_SERVER}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
    depends_on:
      - keycloak
      - broker
      - schema-registry
      - eureka-server
    networks:
      - skillhub-network

  enrollment-service:
    image: enrollment-service:latest
    container_name: enrollment-service
    ports:
      - "${ENROLLMENT_SERVICE_PORT}:${ENROLLMENT_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - ENROLLMENT_SERVICE_PORT=${ENROLLMENT_SERVICE_PORT}
      - TZ=Asia/Ho_Chi_Minh
      # MySQL config
      - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL}
      - MYSQL_DATABASE_USERNAME=${MYSQL_DATABASE_USERNAME}
      - MYSQL_DATABASE_PASSWORD=${MYSQL_DATABASE_PASSWORD}
      # Keycloak config
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      # Kafka config
      - KAFKA_BROKER_BOOTSTRAP_SERVER=${KAFKA_BROKER_BOOTSTRAP_SERVER}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
      # Other services URLs
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      - COURSE_SERVICE_URL=${COURSE_SERVICE_URL}
    depends_on:
      - mysql
      - keycloak
      - broker
      - schema-registry
      - eureka-server
    networks:
      - skillhub-network

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "${EUREKA_PORT:-8761}:8761"
    environment:
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Ho_Chi_Minh
      - PROFILE_SERVICE_PORT=${PROFILE_SERVICE_PORT}
      - COURSE_SERVICE_PORT=${COURSE_SERVICE_PORT}
      - LECTURE_SERVICE_PORT=${LECTURE_SERVICE_PORT}
      - BLOG_SERVICE_PORT=${BLOG_SERVICE_PORT}
      - ASSIGNMENT_SERVICE_PORT=${ASSIGNMENT_SERVICE_PORT}
      - CHAT_SERVICE_PORT=${CHAT_SERVICE_PORT}
    networks:
      - skillhub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ai-service:
    image: ai-service:latest
    container_name: ai-service
    ports:
      - "${AI_SERVICE_PORT}:${AI_SERVICE_PORT}"
    environment:
      # MongoDB config
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=${MONGO_AI_DATABASE}
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      # OpenAI config
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_SERVICE_PORT=${AI_SERVICE_PORT}
      - ENV=development
      - DB_URI=mongodb://localhost:27017
      - TZ=Asia/Ho_Chi_Minh
      - DB_NAME=aiassistant
      - QDRANT_HOST=e47cd5ed-9aed-4817-898a-31345e0d89f0.us-east4-0.gcp.cloud.qdrant.io
      - QDRANT_PORT=6334
      - QDRANT_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.AR8DKBxrvjVQ_uMuQ3Qu8a7ClDOs1TT5RjoxSGhg09M
      - COURSE_SERVICE_URL=${COURSE_SERVICE_URL}
      # Eureka config
      - EUREKA_USERNAME=${EUREKA_USERNAME:-admin}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD:-admin}
      - EUREKA_SERVER_URL=http://${EUREKA_USERNAME:-admin}:${EUREKA_PASSWORD:-admin}@eureka-server:8761/eureka
    depends_on:
      - mongodb
      - eureka-server
      - profile-service
      - course-service
    networks:
      - skillhub-network

volumes:
  mysql_data:
    driver: local
  keycloak_data:
    driver: local

networks:
  skillhub-network:
    driver: bridge