name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
        
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-southeast-1 | \
        docker login --username AWS --password-stdin 116981768488.dkr.ecr.ap-southeast-1.amazonaws.com

    - name: Build & Push Course Service
      run: |
        cd course-service
        docker build -t course-service:latest .

        # Tag lại image theo ECR repo
        docker tag course-service:latest 116981768488.dkr.ecr.ap-southeast-1.amazonaws.com/skillhub/course-service:latest

        # Push lên ECR
        docker push 116981768488.dkr.ecr.ap-southeast-1.amazonaws.com/skillhub/course-service:latest
